---
title: "Shelf_Life"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Adrian D. Garcia"
date: "January 2020"
output: html_document
---

```{r setup, message=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(DT)
```

```{r load, message=FALSE}

a <- "ccccdccccdccdcccnndccccddddd"

Data_1 <- read_csv("Morningstar_Obsolte_X_2008.csv",
                   col_types = a) %>%
  mutate(
    `Obsolete Date` = ymd(`Obsolete Date`),
    Obsolete_Year = year(`Obsolete Date`)
  ) %>%
  filter(Obsolete_Year < 2008)

Data_2 <- read_csv("Morningstar_Obsolte_2008_2014.csv",
                   col_types = a) %>%
  mutate(
    `Obsolete Date` = ymd(`Obsolete Date`),
    Obsolete_Year = year(`Obsolete Date`)
  ) %>%
  filter(between(Obsolete_Year, 2008, 2013))

Data_3 <- read_csv("Morningstar_Obsolte_2014_2019.csv",
                   col_types = a) %>%
  mutate(
    `Obsolete Date` = ymd(`Obsolete Date`),
    Obsolete_Year = year(`Obsolete Date`)
  ) %>%
  filter(between(Obsolete_Year, 2014, 2019))


Full <- full_join(Data_1, Data_2) %>%
  full_join(., Data_3)


```


```{r analysis, message = FALSE}

Full_1 <- Full %>% 
  mutate(
    `Obsolete Date` = ymd(`Obsolete Date`),
    `Inception Date` = ymd(`Inception Date`),
    Obsolete_Year = year(`Obsolete Date`),
    Obsolete_Month = month(`Obsolete Date`),
    Inception_Year = year(`Inception Date`),
    Inception_Month = month(`Inception Date`),
    Survival = ((Obsolete_Year - Inception_Year) * 12) + (Obsolete_Month - Inception_Month)
  )

```

```{r overall}

Overall <- Full_1 %>% 
  group_by(Obsolete_Year) %>% 
  summarise(Count = n(),
            Avg = mean(Survival),
            Mdn = median(Survival))
Overall %>% 
ggplot(mapping = aes(x = `Obsolete_Year`, y = Avg)) + 
  geom_col() +
  labs(y = "Avg Months Alive", title = "Full Data")
```

```{r}
New <- Full_1 %>% 
  filter(Inception_Year >= 2000) %>% 
  group_by(Obsolete_Year) %>% 
  summarise(Count = n(),
            Avg = mean(Survival),
            Mdn = median(Survival))
  
New %>% 
ggplot(mapping = aes(x = `Obsolete_Year`, y = Avg)) + 
  geom_col() +
labs(y = "Avg Months Alive", title = "Share Class Created in 2000s")
```


```{r oldest_share}
Oldest <- Full_1 %>% 
  filter(`Oldest Share Class` == "Yes") %>% 
  group_by(Obsolete_Year) %>% 
  summarise(Count = n(),
            Avg = mean(Survival),
            Mdn = median(Survival))

Oldest %>% 
ggplot(mapping = aes(x = `Obsolete_Year`, y = Avg)) + 
  geom_col() +
    labs(y = "Avg Months Alive", title = "Oldest Class Classes")
```

```{r institutional}

Institutional <- Full_1 %>% 
  filter(`Share Class Type` == "Inst") %>% 
  group_by(Obsolete_Year) %>% 
  summarise(Count = n(),
            Avg = mean(Survival),
            Mdn = median(Survival))

Institutional %>% 
ggplot(mapping = aes(x = `Obsolete_Year`, y = Avg)) + 
  geom_col() +
  labs(y = "Avg Months Alive", title = "Inst. Shares")

```

```{r class}

Class <- Full_1 %>% 
  group_by(Obsolete_Year, `Share Class Type`) %>% 
  summarise(Count = n(),
            Avg = mean(Survival),
            Mdn = median(Survival))


Full_1 %>% 
  filter(Survival < 500) %>% 
ggplot(mapping = aes(x = `Obsolete Date`, y = Survival)) + 
  geom_point(mapping = aes(color = `Share Class Type`)) +
  facet_wrap(~ `Share Class Type`) +
  geom_smooth(method = 'lm', se = FALSE) +
  labs(y = "Months Alive", title = "By Share Class")
```
